name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/HackXIt/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: help wanted, quesetion
          label-operator: NOT
        # You may pin to the exact commit or the version.
        # uses: technote-space/assign-author@314be11408f46898f65485daf142cef4e15453c0
      - uses: technote-space/assign-author@v1.3.1
        with:
          # Secret GitHub API token to use for making API requests.
          GITHUB_TOKEN: ${{ github.token }} # default is ${{ github.token }}
