name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Project
        uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: 'https://github.com/users/HackXIt/projects/7'
          column_name: '📋 Backlog'
      - name: Assign author 
        # You may pin to the exact commit or the version.
        # uses: technote-space/assign-author@314be11408f46898f65485daf142cef4e15453c0
        uses: technote-space/assign-author@v1.3.1
        with:
          # Secret GitHub API token to use for making API requests.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # default is ${{ github.token }}
